CREATE TABLE IF NOT EXISTS
	products(
		id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		name VARCHAR(50) NOT NULL,
		description VARCHAR(50) NOT NULL,
		brand VARCHAR(50) NOT NULL UNIQUE,
        image_url VARCHAR(50) NOT NULL,
        price VARCHAR(50) NOT NULL,
        category VARCHAR(50) NOT NULL,
		created_at TIMESTAMPTZ DEFAULT NOW(),
		updated_at TIMESTAMPTZ DEFAULT NOW()
	);
